  server:
    port: 8081
#  spring:
#    datasource:
#      url: jdbc:mysql://locahost:3306/student?characterEncoting=utf-8
#      username: root
#      password: 123123
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      type: com.alibaba.driver.pool.DriverDataSource
